### ISSUE TITLE
Unable to start singleface.py

### ISSUE THREAD

**Issue by luke110206** [atulapra/Emotion-detection#20]
I get this when I run python3 model.py singleface
`Traceback (most recent call last):
  File "model.py", line 3, in <module>
    import tflearn
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tflearn/__init__.py", line 4, in <module>
    from . import config
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tflearn/config.py", line 5, in <module>
    from .variables import variable
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tflearn/variables.py", line 7, in <module>
    from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope
ModuleNotFoundError: No module named 'tensorflow.contrib'`
I'm running MacOS High Sierra

**Comment by atulapra** [comment]
Please check your tensorflow version. This code will not work for tensorflow version 2.0.
